TELEGRAM_API_TOKEN = ""

MONGODB_URI = ""
DATABASE_NAME = "ktb-db-test"

ADMIN_CHAT_ID = 0
LOGGER_CHAT_ID = 0

PRICE_CHECK_HOURS = [10, 15]
PRICE_CHECK_MINUTES = [0, 0]

WEBHOOK_CONNECTED = false
PORT = 31415
WEBHOOK_URL = ""
WEBHOOK_BIND = "0.0.0.0"
